# Generated by Django 4.2 on 2022-11-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0010_store_store_name_display_only"),
        ("products", "0006_alter_product_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                help_text="이 상품을 판매하는 가게", on_delete=django.db.models.deletion.CASCADE, to="stores.store"
            ),
        ),
    ]
