# Generated by Django 4.2 on 2022-11-06 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0010_store_store_name_display_only"),
        ("products", "0010_alter_product_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                db_column="store_new_id",
                db_comment="새로 다시 상점 외래키입니다.333",
                help_text="이 상품을 판매하는 가게",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_new",
                to="stores.store",
            ),
        ),
    ]
