# Generated by Django 4.2.2 on 2023-06-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stores", "0002_store_description_delete_storetext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="상품명", max_length=128)),
                ("price", models.IntegerField(help_text="상품 가격")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("grocery", "식료품"),
                            ("furniture", "가구"),
                            ("books", "책"),
                            ("food", "음식"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        help_text="이 상품을 판매하는 가게",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_new",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "product",
                "db_table_comment": "상품 테이블 입니다.",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="BooksProduct",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="FurnitureProduct",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.product",),
        ),
        migrations.CreateModel(
            name="GroceryProduct",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.product",),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_at"], name="created_at_index"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name", "product_type"], name="name_pt_composite_index"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                check=models.Q(("price__lte", 100000000)),
                name="check_unreasonalbe_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(fields=("store", "name", "product_type"), name="unique_in_store"),
        ),
    ]
