# Generated by Django 4.0.3 on 2022-05-21 07:06

from django.db import migrations, transaction

from aggregate.users.models import Organization


def bulk_create_organization_data(apps, schema_editor):
    Organization.objects.bulk_create(
        objs=[
            Organization(pk=1, name="인사팀"),
            Organization(pk=2, name="개발팀"),
            Organization(pk=3, name="재무팀"),
            Organization(pk=4, name="디자인팀"),
            Organization(pk=5, name="영업팀"),
        ],unique_fields=["pk"]
    )


def bulk_delete_organization_data(apps, schema_editor):
    Organization.objects.filter(
        name__in=["인사팀", "개발팀", "재무팀", "디자인팀", "영업팀"],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_organization_name'),
    ]

    operations = [
        # (1) 과 (2)는 동일한 동작을 수행합니다.

        # (1)
        migrations.RunPython(
            code=bulk_create_organization_data, reverse_code=bulk_delete_organization_data,
        ),

        # (2)
        # migrations.RunSQL(
        #     sql="""INSERT INTO users_organization( org_name )
        #                 VALUES ('인사팀'), ('개발팀'), ('재무팀'), ('디자인팀'), ('영업팀');
        #     """,
        #     reverse_sql="""DELETE FROM users_organization
        #             WHERE name IN ('인사팀', '개발팀', '재무팀', '디자인팀', '영업팀');
        #     """
        #
        # )
    ]
