# Generated by Django 4.2.1 on 2023-06-18 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "active",
                    models.BooleanField(
                        db_comment="this field should be controlled by changes in the Contract start_date and end_date",
                        default=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("tel_num", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("food", "FoodDelivery"),
                            ("grocery", "MorningGroceryDelivery"),
                            ("pet_equipment", "PetEquipmentDelivery"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "owner",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "store",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sales_commission", models.DecimalField(decimal_places=2, max_digits=5)),
                ("start_date", models.DateField(db_comment="store active will be True ", null=True)),
                ("end_date", models.DateField(db_comment="store active will be False", null=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="sample_app.store")),
            ],
            options={
                "db_table": "contract",
                "db_table_comment": "Store Contract",
            },
        ),
    ]
