# Generated by Django 3.1.4 on 2021-07-25 05:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210725_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='HModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'h_model',
            },
        ),
    ]
