# Generated by Django 3.1.4 on 2021-07-25 05:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmodel',
            name='aa',
            field=models.CharField(default='qqqqq', help_text='help_text', max_length=64),
        ),
    ]
