[tool.poetry]
name = "django_backend_starter_project"
version = "1.0.0"
description = "django backend starter project"
authors = ["SoungRyoul Kim <KimSoungRyoul@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11.0"

# django
django = "^4.2"
django-filter = "^2.4.0"
django-extensions = "^3.0.9"
channels = {extras = ["daphne"], version = "^4.0.0"}

# django rest framework
djangorestframework = "3.14.0"
drf-spectacular = "^0.26.2"
djangorestframework-simplejwt = "^5.1.0"

# CACHES
#django-redis = "^5.2.0"

# mysql
# mysqlclient = "^2.0.3"
# django-mysql = "^3.12.0"

# postgresql
#psycopg = {extras = ["binary", "pool"], version = "^3.1.8"}
#django-postgres-extra = "^2.0.8"

mypy = "^1.2"
django-stubs = { extras = ["compatible-mypy"], version = "^4.2.0" }
djangorestframework-stubs = "^1.4.0"
gunicorn = "^20.1.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}

[tool.poetry.group.dev.dependencies]
ipython = "^8.3.0"
pre-commit = "^2.9.3"
Werkzeug = "^2.0.3"
black = "^23.3.0"


[tool.poetry.group.test.dependencies]
freezegun = "^1.2.2"


[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | node_modules
    | docs
    | venv
    | templates
  )
)
'''

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version = "3.11"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
implicit_reexport = false
strict_optional = true
strict_equality = true
no_implicit_optional = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unreachable = true
warn_no_return = true
plugins = ["mypy_django_plugin.main", "mypy_drf_plugin.main"]


[tool.django-stubs]
django_settings_module = "config.settings"
