# Generated by Django 3.1.4 on 2021-08-06 02:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleuser',
            name='aaa',
            field=models.CharField(default='dd', max_length=12),
        ),
    ]
