# Generated by Django 3.1.4 on 2021-04-28 13:07

from django.db import migrations, models
import study_example_app.models.file_field_example_models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefieldexamplemodel',
            name='file',
            field=models.FileField(max_length=256, null=True, upload_to=study_example_app.models.file_field_example_models.upload_filepath),
        ),
        migrations.AlterField(
            model_name='filefieldexamplemodel',
            name='image',
            field=models.ImageField(max_length=256, upload_to=study_example_app.models.file_field_example_models.upload_filepath),
        ),
    ]
