# Generated by Django 3.1.4 on 2021-08-06 02:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0003_auto_20210806_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleuser',
            name='bbb',
            field=models.CharField(default='erefrerere', max_length=34),
            preserve_default=False,
        ),
    ]
