# Generated by Django 3.1.4 on 2021-01-26 10:37

from django.db import migrations
import study_example_app.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0003_bmodel_b_masking_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='amodel',
            name='a_masking_field',
            field=study_example_app.models.fields.MaskingField(default='aa', max_length=32),
        ),
    ]
