# Generated by Django 3.1.4 on 2021-02-13 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0004_amodel_a_masking_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleuser',
            name='a_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='study_example_app.amodel'),
        ),
    ]
