# Generated by Django 3.1.4 on 2021-08-06 02:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0004_exampleuser_bbb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleuser',
            name='aaa',
            field=models.CharField(max_length=33),
        ),
    ]
