# Generated by Django 3.1.4 on 2021-02-13 06:09

from django.db import migrations, models
import django.db.models.deletion
import study_example_app.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('study_example_app', '0005_exampleuser_a_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('m_field', models.CharField(max_length=16)),
                ('m_int_field', models.IntegerField(default=3)),
                ('m_masking_field', study_example_app.models.fields.MaskingField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('b_field', models.CharField(max_length=16)),
                ('b_int_field', models.IntegerField(default=3)),
                ('b_masking_field', study_example_app.models.fields.MaskingField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('a_field', models.CharField(max_length=16)),
                ('a_int_field', models.IntegerField(default=3)),
                ('a_masking_field', study_example_app.models.fields.MaskingField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
