# Generated by Django 3.1.4 on 2021-08-06 02:35
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0005_auto_20210806_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampleuser',
            name='bbb',
            field=models.CharField(help_text='나는 주석입니다.', max_length=34),
        ),
    ]
