# Generated by Django 3.1.4 on 2021-02-14 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0006_album_book_consumer_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음식점 가게명', max_length=128)),
                ('tel_num', models.CharField(help_text='음식점 연락처', max_length=16)),
            ],
            options={
                'db_table': 'rest2',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='음식 메뉴이름', max_length=128)),
                ('price', models.IntegerField(help_text='음식 가격')),
                ('restaurant', models.ForeignKey(help_text='이 메뉴를 판매하는 음식정', on_delete=django.db.models.deletion.CASCADE, to='study_example_app.restaurant2')),
            ],
        ),
    ]
