# Generated by Django 3.1.4 on 2021-02-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0007_menu_restaurant2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='rest3',
        ),
    ]
