# Generated by Django 3.1.4 on 2021-08-06 02:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0007_auto_20210806_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampleuser',
            name='ccc',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
