# Generated by Django 3.1.4 on 2021-02-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0008_auto_20210214_0903'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant2',
            table='restaurant',
        ),
    ]
