# Generated by Django 3.1.4 on 2021-02-26 11:04

from django.db import migrations, models
import django.db.models.deletion
import study_example_app.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('study_example_app', '0009_auto_20210214_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('m_field', models.CharField(max_length=16)),
                ('m_int_field', models.IntegerField(default=3)),
                ('m_masking_field', study_example_app.models.fields.MaskingField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'movie22',
            },
        ),
    ]
