# Generated by Django 3.1.4 on 2021-02-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0010_movie2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='m_field',
            new_name='m_field22',
        ),
    ]
