# Generated by Django 3.1.4 on 2021-02-26 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0012_auto_20210226_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
