# Generated by Django 4.0.3 on 2022-05-21 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_organization"),
    ]

    operations = []
