# Generated by Django 4.1.7 on 2023-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_example_app', '0003_company_department_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aa',
            field=models.DateTimeField(null=True),
        ),
    ]
