# Generated by Django 4.2 on 2023-04-23 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study_example_app", "0004_student_aa"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Department",
            new_name="Department1",
        ),
    ]
