# Generated by Django 3.2.6 on 2021-09-22 12:40
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20210922_1218"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name_kor",
            field=models.CharField(default="", help_text="회원 성함(한국어)", max_length=64),
            preserve_default=False,
        ),
    ]
