name: django-backend-starter-compose
services:
  django-backend-postgres-db:
    image: postgres:15.2
    container_name: django-backend-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: django_db

  django-backend-mysql-db:
    image: mysql:8.0.33
    container_name: django-backend-mysql-db
    ports:
      - "3306:3306"
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: django_db
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_PASSWORD: 1234
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  django-backend-redis:
    image: redis:7.0.11
    container_name: django-backend-redis
    ports:
      - "6379:6379"
