# Generated by Django 3.2.9 on 2021-11-07 08:03
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_auto_20211107_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetext',
            old_name='text',
            new_name='contents',
        ),
    ]
