# Generated by Django 4.2 on 2023-04-23 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_create_dailyreport_vmodel"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="orderedproduct",
            table_comment="주문된 상품, Order와 Product사이 매핑테이블",
        ),
    ]
