# Generated by Django 3.2.6 on 2021-08-08 11:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_price", models.IntegerField(default=0)),
                ("address", models.CharField(help_text="주문 배송지", max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="OrderedProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField(default=1, help_text="주문한 해당 메뉴의 갯수")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.order")),
            ],
            options={
                "db_table": "ordered_product",
            },
        ),
    ]
