# Generated by Django 3.2.6 on 2021-08-08 11:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.product"),
        ),
        migrations.AddField(
            model_name="order",
            name="product_set",
            field=models.ManyToManyField(through="orders.OrderedProduct", to="products.Product"),
        ),
    ]
