# Generated by Django 4.0.3 on 2022-05-21 07:06

from django.db import migrations, transaction

from aggregate.users.models import Organization


def bulk_create_organization_data(apps, schema_editor):
    Organization.objects.bulk_create(
        objs=[
            Organization(name="인사팀"),
            Organization(name="개발팀"),
            Organization(name="재무팀"),
            Organization(name="디자인팀"),
            Organization(name="영업팀"),
        ]
    )


def bulk_delete_organization_data(apps, schema_editor):
    Organization.objects.filter(
        name__in=["인사팀", "개발팀", "재무팀", "디자인팀", "영업팀"],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211017_0925'),
        ('users', '0007_organization'),
    ]

    operations = [
        migrations.RunPython(
            code=bulk_create_organization_data, reverse_code=bulk_delete_organization_data,
        ),
        migrations.RunSQL(
            sql="""INSERT INTO users_organization(`name`)
                        VALUES ('인사팀'), ('개발팀'), ('재무팀'), ('디자인팀'), ('영업팀');
            """,
            reverse_sql="""DELETE FROM users_organization
                    WHERE name IN ('인사팀', '개발팀', '재무팀', '디자인팀', '영업팀');
            """

        )
    ]
