# Generated by Django 4.1.3 on 2022-11-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0010_store_store_name_display_only"),
        ("products", "0003_alter_product_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store22",
            field=models.ForeignKey(
                help_text="이 상품을 판매하는 가게",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product22",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                help_text="이 상품을 판매하는 가게",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_new",
                to="stores.store",
            ),
        ),
    ]
