# Generated by Django 4.2 on 2023-04-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_customer2_purchasedescriptions'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='product',
            table_comment='상품 테이블 입니다.',
        ),
        migrations.RemoveField(
            model_name='product',
            name='store22',
        ),
    ]
