# Generated by Django 3.2.6 on 2021-09-28 08:21
from django.db import migrations

import study_example_app.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_name_kor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=study_example_app.models.fields.EncryptedField(blank=True, help_text='주민등록번호', max_length=64),
        ),
    ]
