# Generated by Django 3.2.6 on 2021-09-28 17:28
from django.db import migrations

import aggregate.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_registration_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', aggregate.users.models.UserManager()),
            ],
        ),
    ]
