# Generated by Django 4.2.2 on 2023-06-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ("pk",)},
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["name"], name="store_name_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["created_at", "store_type"], name="cr_at_type_composite_idx"),
        ),
    ]
