# Generated by Django 4.2.1 on 2023-05-29 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_comment="음식점 가게명", max_length=128)),
                ("tel_num", models.CharField(db_comment="음식점 연락처", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "store_type",
                    models.CharField(
                        choices=[("food", "배달음식"), ("grocery", "식료품/가공식품"), ("pet_food", "반려동물음식")],
                        db_comment="상점 유형",
                        max_length=32,
                    ),
                ),
                (
                    "store_name_display_only",
                    models.CharField(db_comment="직원이 해당 상점을 한눈에 볼수있게 관리하는 필드입니다.", max_length=128),
                ),
            ],
            options={
                "db_table": "store",
                "db_table_comment": "상점",
            },
        ),
        migrations.CreateModel(
            name="StoreAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("si", models.CharField(db_comment="시", max_length=128)),
                ("gu", models.CharField(db_comment="구", max_length=128)),
                ("gun", models.CharField(db_comment="군", max_length=128)),
                ("dongmyun", models.CharField(db_comment="동,면,읍", max_length=128)),
                ("lat", models.FloatField(db_comment="위도")),
                ("lng", models.FloatField(db_comment="경도")),
                ("detail", models.CharField(db_comment="상세 주소", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="StoreText",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "text_type",
                    models.CharField(choices=[("legal_notice", "법적 고시"), ("origin", "원산지 정보")], max_length=32),
                ),
                ("contents", models.TextField(db_comment="대용량 텍스트")),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.store")),
            ],
        ),
        migrations.CreateModel(
            name="StoreActiveSwitch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "switch_type",
                    models.CharField(choices=[("is_open", "현재 영업 여부"), ("has_ad_mark", "현재 광고상품 사용여부")], max_length=32),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.store")),
            ],
        ),
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="stores.storeaddress"
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sales_commission", models.DecimalField(db_comment="판매 수수료(%)", decimal_places=2, max_digits=5)),
                ("start_date", models.DateField(db_comment="계약 시작날짜", null=True)),
                ("end_date", models.DateField(db_comment="계약 종료날짜", null=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="stores.store")),
            ],
        ),
    ]
