# Generated by Django 4.2.2 on 2023-06-25 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="description",
            field=models.TextField(db_comment="상점 소개 문구", default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="StoreText",
        ),
    ]
