# Generated by Django 3.1.4 on 2021-07-27 06:42
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='상품명', max_length=128)),
                ('price', models.IntegerField(help_text='상품 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.CharField(choices=[('grocery', '식료품'), ('furniture', '가구'), ('books', '책')], max_length=32)),
                ('store', models.ForeignKey(help_text='이 상품을 판매하는 가게', on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'product',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BooksProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='FurnitureProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='GroceryProduct',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.product',),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='created_at_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'product_type'], name='name_pt_composite_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.HashIndex(fields=['name'], name='name_hash_index'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(price__lte=100000000), name='check_unreasonalbe_price'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'name', 'product_type'), name='unique_in_store'),
        ),
    ]
