# Generated by Django 4.0.3 on 2022-03-31 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='학교이름', max_length=64)),
                ('date_established', models.DateField(help_text='설립일자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'university',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('major_type', models.CharField(choices=[('engineering', '공학계열'), ('business', '상경계열')], max_length=32)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_example_app.university')),
            ],
            options={
                'db_table': 'major',
            },
        ),
    ]
