# Generated by Django 4.2 on 2022-11-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_store_name_display_only'),
        ('products', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='생성날짜 입니다.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_comment='상품 가격....', help_text='상품 가격'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(db_comment='상점 외래키입니다.', help_text='이 상품을 판매하는 가게', on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
        migrations.AlterModelTableComment(
            name='product',
            db_table_comment='상품 테이블 입니다.',
        ),
    ]
