# Generated by Django 4.2 on 2022-11-06 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0010_store_store_name_display_only"),
        ("products", "0004_alter_product_created_at_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="store22",
            field=models.ForeignKey(
                db_comment="상점222 외래키입니다.",
                help_text="이 상품을 판매하는 가게",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product22",
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(help_text="상품 가격"),
        ),
        migrations.AlterModelTableComment(
            name="product",
            db_table_comment=None,
        ),
    ]
