# Generated by Django 4.2 on 2022-11-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0010_store_store_name_display_only"),
        ("products", "0005_product_store22_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                db_comment="상점 외래키입니다.2222",
                help_text="이 상품을 판매하는 가게",
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
