# Generated by Django 3.2.6 on 2021-08-22 10:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_store_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
